[LegalNotice]
Accepted=true

[BitTorrent]
Session\DefaultSavePath=__DOWNLOADS_DIR__
Session\TempPath=__INCOMPLETE_DIR__
Session\TempPathEnabled=true
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\MaxActiveDownloads=3
Session\MaxActiveTorrents=5
Session\MaxActiveUploads=3

[Preferences]
Connection\PortRangeMin=6881
Downloads\SavePath=__DOWNLOADS_DIR__
Downloads\TempPath=__INCOMPLETE_DIR__
Downloads\TempPathEnabled=true
Downloads\PreAllocation=false
Downloads\UseIncompleteExtension=true
WebUI\Enabled=true
WebUI\Address=*
WebUI\Port=__PORT__
WebUI\LocalHostAuth=false
WebUI\Username=admin
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=false
General\Locale=pt_BR
General\UseRandomPort=false
Advanced\RecheckOnCompletion=false
